#!/bin/bash
set -e  # Stop script on error

export PICO_SDK_PATH=~/pico-sdk

SCRIPT_DIR=$(dirname "$(realpath "$0")")
cd "$SCRIPT_DIR"

rm -rf outdir
mkdir outdir
cd outdir
cmake ..
make # -j$(nproc)
cd ..
cp outdir/blink.uf2 ./blink.uf2
rm -rf outdir
echo "Copy blink.uf2 to the pico in boootsel mode"
# wait for /media/gorak/RPI-RP2/ to appear
while [ ! -d /media/gorak/RPI-RP2/ ]; do
  sleep 1
done
cp blink.uf2 /media/gorak/RPI-RP2/

