name: "UF2 Release"
description: "Uploads blink.uf2 as a release, auto-incrementing the patch version"
inputs:
  major_minor_version:
    description: "Major.Minor version (e.g., v1.0)"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get latest release tag
      shell: bash
      run: |
        MAJOR_MINOR="${{ inputs.major_minor_version }}"
        LATEST_TAG=$(git tag -l "${MAJOR_MINOR}.*" | sort -V | tail -n1)

        if [ -z "$LATEST_TAG" ]; then
          NEXT_TAG="${MAJOR_MINOR}.0"
        else
          PATCH_VERSION=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
          NEXT_PATCH=$((PATCH_VERSION + 1))
          NEXT_TAG="${MAJOR_MINOR}.${NEXT_PATCH}"
        fi

        echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
        echo "Next version: $NEXT_TAG"

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: blink.uf2
        tag_name: ${{ env.NEXT_TAG }}
        release_name: Blink Firmware ${{ env.NEXT_TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
