name: Build and Release

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up pico-sdk
              run: bash get_pico_sdk
            - name: Set up arm-none-eabi-gcc
              run: bash get_gcc
            - name: Build project
              run: bash build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UF2
                  path: blink.uf2
            - name: Upload UF2 release
              uses: ./.github/actions/release/versioned_release.yml  # Uses the local composite action
              with:
                major_minor_version: "v1.0"
                github_token: ${{ secrets.GITHUB_TOKEN }}