name: Build and Release

on:
  push:
    branches:
      - main

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up pico-sdk
              run: bash get_pico_sdk
            - name: Set up arm-none-eabi-gcc
              run: bash get_gcc
            - name: Build project
              run: bash build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UF2
                  path: blink.uf2
    release:
        runs-on: ubuntu-latest
        needs: build-and-upload
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get artifact
              uses: actions/download-artifact@v4
              with:
                  name: UF2
            - name: Get latest release tag
              shell: bash
              run: |
                    MAJOR_MINOR="v1.0"
                    LATEST_TAG=$(git tag -l "${MAJOR_MINOR}.*" | sort -V | tail -n1)
                    if [ -z "$LATEST_TAG" ]; then
                        NEXT_TAG="${MAJOR_MINOR}.0"
                    else
                        PATCH_VERSION=$(echo "$LATEST_TAG" | awk -F. '{print $3}')
                        NEXT_PATCH=$((PATCH_VERSION + 1))
                        NEXT_TAG="${MAJOR_MINOR}.${NEXT_PATCH}"
                    fi
                    echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
                    echo "Next version: $NEXT_TAG"
            - name: Upload release
              uses: softprops/action-gh-release@v1
              with:
                files: blink.uf2
                tag_name: ${{ env.NEXT_TAG }}
                name: Blink Firmware ${{ env.NEXT_TAG }}
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}