name: Build and Release

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            #   cmake
            - name: Build project
              run: cmake
            - name: debug ls
              run: |
                ls
                ls build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UF2
                  path: build/*.uf2
                