name: Build and Release

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            #   cmake
            - name: Build project
              run: cmake -B build -S .
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UF2
                  path: build/*.uf2
                